const API_KEY = "47223dc77b02e3169fa9047461b75c36";
const requests = {
    fetchTrending: `/trending/all/day?api_key=${API_KEY}`,
    fetchTrendingMovie: `/trending/movie/week?api_key=${API_KEY}`,
    fetchTrendingTV: `/trending/tv/day?api_key=${API_KEY}`,
    fetchTopRated: `/movie/top_rated?api_key=${API_KEY}`,
    fetchAdventureMovie: `/discover/movie?api_key=${API_KEY}&with_genres=12`,
    fetchNetflixOriginalsMovie: `/discover/movie?api_key=${API_KEY}&with_networks=213`,
    fetchNetflixOriginalsTV: `/discover/tv?api_key=${API_KEY}&with_networks=213`,
    fetchComedyMovie: `/discover/movie?api_key=${API_KEY}&with_genres=35`,
    fetchComedyTV: `/discover/tv?api_key=${API_KEY}&with_genres=35`,
    fetchRomanceMovie: `/discover/movie?api_key=${API_KEY}&with_genres=10749`,
    fetchRomanceTV: `/discover/tv?api_key=${API_KEY}&with_genres=10749`,
    fetchActionMovie: `/discover/movie?api_key=${API_KEY}&with_genres=28`,
    fetchActionTV: `/discover/tv?api_key=${API_KEY}&with_genres=28`,
    fetchDocumentaryMovie: `/discover/movie?api_key=${API_KEY}&with_genres=99`,
    fetchDocumentaryTV: `/discover/tv?api_key=${API_KEY}&with_genres=99`,
    fetchFantasyMovie: `/discover/movie?api_key=${API_KEY}&with_genres=14`,
    fetchFantasyTV: `/discover/tv?api_key=${API_KEY}&with_genres=14`,
    fetchThrillerMovie: `/discover/movie?api_key=${API_KEY}&with_genres=53`,
    fetchThrillerTV: `/discover/tv?api_key=${API_KEY}&with_genres=53`,
    fetchScifiMovie: `/discover/movie?api_key=${API_KEY}&with_genres=878`,
    fetchScifiTV: `/discover/tv?api_key=${API_KEY}&with_genres=878`,
    fetchAnimationMovie: `/discover/movie?api_key=${API_KEY}&with_genres=16`,
    fetchAnimationTV: `/discover/tv?api_key=${API_KEY}&with_genres=16`,
};

export const genre_list = [
    "TRENDING",
    "TRENDING_TV",
    "TRENDING_MOVIE",
    "TOPRATED",
    "COMEDY_MOVIE",
    "COMEDY_TV",
    "ADVENTURE_MOVIE",
    "ADVENTURE_TV",
    "NORIGINALS_MOVIE",
    "NORIGINALS_TV",
    "COMEDY_MOVIE",
    "COMEDY_TV",
    "ROMANCE_TV",
    "ROMANCE_MOVIE",
    "ACTION_TV",
    "ACTION_MOVIE",
    "DOCUMENTARY_MOVIE",
    "DOCUMENTARY_TV",
    "FANTASY_MOVIE",
    "FANTASY_TV",
    "THRILLER_MOVIE",
    "THRILLER_TV",
    "SCIFI_TV",
    "SCIFI_MOVIE",
    "ANIMATION_MOVIE",
    "ANIMATION_TV",
];

export default requests;
